#
# file:		test_pull_to_master.yml
#

name: test_pull_to_master
on:
    pull_request:
        branches: [ master ]

jobs:

    # matrix for debian linuxes (for now ubuntu-18.04 and ubuntu-20.04)
    unixes:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        steps:
            - uses: actions/checkout@v3
           
            - name: Preparing 3rd party libraries for ${{ matrix.os }}
              run: ./scripts/.cicd/unix_prebuild.sh

            - name: Compiling for ${{ matrix.os }}
              #run: ./scripts/.cicd/unix_test_pull_to_master_build.sh CPPUTILS_DEBUG=1
              run: ./scripts/.cicd/unix_test_pull_to_master_build.sh CPPUTILS_DEBUG=1
              #working-directory: blabla

            - name: running unittest for ${{ matrix.os }}
              run: ./scripts/.cicd/unix_test_pull_to_master_unittest.sh	Debug
            
    # This is for windows
    windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v3

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.1
              with:
                  vs-version: 16.10.4

            - name: Setup developer command prompt
              uses: ilammy/msvc-dev-cmd@v1
              #with:
              #    toolset: v142

            - name: Preparing 3rd party libraries for windows
              run: .\scripts\.cicd\windows_prebuild.bat

            #- name: Compiling for windows
              #run: .\scripts\.cicd\windows_test_pull_to_master_build.bat
              #working-directory: blabla

            #- name: running unittest for windows
              #run: .\scripts\.cicd\windows_test_pull_to_master_unittest.bat

